import { Router } from "next/router";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html style={{height:"100%", overflowX:"hidden"}} lang="en">
      <body>{children}</body>
    </html>
  );
}
